# Generated by Django 6.0.4 on 2026-04-26 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100, verbose_name='Автор')),
                ('content', models.TextField(verbose_name='Мазмұн')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Жазылған уақыт')),
            ],
            options={
                'verbose_name': 'Түсініктеме',
                'verbose_name_plural': 'Түсініктемелер',
                'ordering': ['-created_at'],
            },
        ),
    ]
